# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    ENV['LC_ALL']="en_US.UTF-8"

    if Vagrant.has_plugin?("vagrant-timezone")
        config.timezone.value = "America/Sao_Paulo"
    end

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    # This configuration is only here to avoid cloudimg-console.log
    config.vm.provider "virtualbox" do |vb|
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end

    config.vm.define "web", primary: true do |web_config|
        # Every Vagrant development environment requires a box. You can search for
        # boxes at https://atlas.hashicorp.com/search.
        web_config.vm.box = "ubuntu/xenial64"
        # Provider default
        web_config.vm.provider "virtualbox"
        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        web_config.vm.network "forwarded_port", guest: 8000, host: 8000
        # Share an additional folder to the guest VM. The first argument is
        # the path on the host to the actual folder. The second argument is
        # the path on the guest to mount the folder. And the optional third
        # argument is a set of non-required options.
        web_config.vm.synced_folder ".", "/home/ubuntu/project"

        # Enable provisioning with a shell script.
        web_config.vm.provision "shell", path: "scripts/init.sh"
        web_config.vm.provision "puppet" do |puppet|
            puppet.manifest_file = "web.pp"
            puppet.manifests_path = "puppet/manifests"
            puppet.module_path = "puppet/modules"
        end
    end
end
